# Generated by Django 2.1.5 on 2019-02-27 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_website', models.TextField(null=True)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(null=True)),
                ('website', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='animation',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Animation_urls.Type'),
        ),
    ]
