# Generated by Django 2.1.5 on 2019-02-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animation_urls', '0002_auto_20190228_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='read',
            field=models.IntegerField(default=0),
        ),
    ]
