# Generated by Django 2.1.5 on 2019-03-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Animation_urls', '0004_auto_20190307_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='read',
            name='name',
        ),
        migrations.DeleteModel(
            name='Read',
        ),
    ]
