# Generated by Django 2.1.7 on 2019-03-26 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Animation_urls', '0005_auto_20190307_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Animation_urls.Type'),
        ),
    ]
