# Generated by Django 2.1.7 on 2019-03-26 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Count', '0002_countdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
