# Generated by Django 2.1.7 on 2019-03-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Count', '0003_auto_20190326_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdate',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
